"""
Django settings for list project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from config.settings.base import *

DEBUG = True


# Application definition

INSTALLED_APPS += [
's3_folder_storage',
'storages'
]


STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"config/static")

STATIC_URL = '/static/'

